### ISSUE TITLE
saving deploy config

### ISSUE THREAD

**Issue by daniyar4m** [sunggun-yu/jenkins-capitomcat-plugin#27]
Hi, i am experiencing following issue, i have installed capitomcat 0.1.0 plugin on my jenkins 1.605, i am able to pick "depoy war file to Tomcat via Capitomcat" from a context menu, and form will show up. But as soon as i would hit save button, none of my settings would save anywhere. If i go to the project settings page again, all of them are gone. Im running jenkins on a Tomcat Server 7.0.41 my os is Ubuntu 12. I'v tried to use the plugin on other machine: windows 7, tomcat 8, jenkins 1.605, the "depoy war file to Tomcat via Capitomcat"  is not present in a context menu. Thank you.

**Comment by PatrickHuetter** [comment]
Hi, i've the same problem on a jenkins 1.602 on my debian wheezy system (installed via apt-get).

**Comment by daniyar4m** [comment]
Hi Patrick, you don't have "deploy war file to Tomcat via Capitomcat"  in context menu or you cant save configuration ? ether way,  any idea how to solve the problem ? thanks.

**Comment by PatrickHuetter** [comment]
@daniyar4m I can't save the configuration. I have no idea how to fix this. The logs say nothing.

**Comment by sunggun-yu** [comment]
@PatrickHuetter @daniyar4m 
I really sorry for the late reply. current I'm working on this. It seems like related to the Jenkins version.
I'll update the progress.
Thank you.

**Comment by sunggun-yu** [comment]
https://github.com/jenkinsci/jenkins.rb/issues/112

**Comment by sunggun-yu** [comment]
https://github.com/melezhik/chef-plugin/issues/4

**Comment by daniyar4m** [comment]
@sunggun-yu thank you for update, i might try downgrading and use ruby runtime 0.10, just to try out, but its still does not work on new jenkins versions, and for other plugins, sometimes i think jenkins is so inconstant, for some reason my active directory plugin does not work in chrome, and works only in firefox, reload button after installing plugin is not available in chrome

**Comment by sunggun-yu** [comment]
@daniyar4m, @PatrickHuetter 
It seems fixed in 1.610. I just tested saving config. I'm going to test full functionality.
Thank you.

**Comment by daniyar4m** [comment]
@sunggun-yu thanks ill check asap
